### ISSUE TITLE
Missing folders should not yield compiler errors

### ISSUE THREAD

**Issue by trajano** [sonatype/m2eclipse-scala#19]
In some projects there can be no src/main/java or src/test/java.  This should not generate an error.

```
Error in Scala compiler: C:\Projects\maven-jee6\behavior-driven-testing\src\test\java does not exist or is not a directory
```

**Comment by slandelle** [comment]
+1
This on didn't happen with 3.0.2

**Comment by slandelle** [comment]
Moreover, test/scala is no longer automatically added so the source directories.

**Comment by davidB** [comment]
Hi,

I didn't find solution on side of this plugin (I did lot of tried). The issue come from :
- m2e who add every sourceRoots and testRoots define in the pom.xml regardless of existance, but mark them optional (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=361549). I create a simple project with only a pom.xml, no directory, and I uninstall m2e-scala, and m2e import a java project with missing source folder (see Build Path)
- scala-ide that didn't ignore non-existing directory and failed when it try to compile.
- scala-maven-plugin, since 3.0.2, it change management of source/add-source (my own) see http://davidb.github.com/scala-maven-plugin/changes-report.html#a3.0.2

My suggestions :
- for pure scala project set
  
  ```
  <sourceDirectory>src/main/scala</sourceDirectory>
  <testSourceDirectory>src/test/scala</testSourceDirectory>
  ```
- create at least the directory define in <testSourceDirectory> (with a .keep file for the SCM)

Stephane I applied those change in my fork of gatling. (I can make a pull request if who whish). I redefine sourceDirectory and testSourceDirectory in every scala project, but you can choose to do the opposite define them to scala directory into the parent and redefine in java sub-module.

During the analyse I made some change in m2e-scala, so next version will no longer add implicit the scala directory to match the change made in scala-maven-plugin and m2e 0.12

/davidB

PS: Sorry for late reply, I didn't receive notification

**Comment by slandelle** [comment]
I confirm that forcing the directories did the trick.
Thanks!

**Comment by fanf** [comment]
It seems to be corrected in recent Scala IDE: https://github.com/scala-ide/scala-ide/pull/262

**Comment by slandelle** [comment]
Thanks for the pointer, François!
